######################## default configuration ####################
baseURL = "/"
title = "HKMMS"
theme = "omega"
# google analytics
googleAnalytics = "" # example : UA-123-45
[markup.goldmark.renderer]
unsafe= true

######################### navigation ##############################

# [[menu.main]]
# name = "Services"
# pre = ""
# URL = "career"
# weight = 1


# [[menu.main]]
# name = "Advantages"
# pre = "#"
# URL = "products"
# weight = 2


# [[menu.main]]
# name = "Contact"
# pre = "#"
# URL = "contact"
# weight = 3

# [[menu.main]]
# name = "About"
# pre = "#"
# URL = "mission"
# weight = 4

# #################### default parameters ################################
 [params]
 logo = "images/logo.png"
 logo_width = "120px"
# # Meta data
# description = "This is meta description"
# author = "Sharad Gadhiya"
# # contact info
# contact_info = ""
# # Preloader
# preloader = true
# # google map
# [params.map]
# enable = false
# gmap_api = ""
# map_center_lat = ""
# map_center_lng = ""
# map_position_lat = ""
# map_position_lng = ""
# map_marker = ""

# # cookies
# [params.cookies]
# enable = true
# expire_days = 2

############################# social site ########################
# [[params.social]]
# title = "facebook"
# icon = "fa-facebook" # fontawesome icon pack v4.7 https://fontawesome.com/v4.7.0/icons/
# link = "#"

# [[params.social]]
# title = "twitter"
# icon = "fa-twitter" # fontawesome icon pack v4.7 https://fontawesome.com/v4.7.0/icons/
# link = "#"

# [[params.social]]
# title = "instagram"
# icon = "fa-instagram" # fontawesome icon pack v4.7 https://fontawesome.com/v4.7.0/icons/
# link = "#"

# [[params.social]]
# title = "github"
# icon = "fa-github" # fontawesome icon pack v4.7 https://fontawesome.com/v4.7.0/icons/
# link = "#"

# [[params.social]]
# title = "linkedin"
# icon = "fa-linkedin" # fontawesome icon pack v4.7 https://fontawesome.com/v4.7.0/icons/
# link = "#"