######################## default configuration ####################
baseURL = "/"
title = "HKMMS"
theme = "omega"
# google analytics
googleAnalytics = "" # example : UA-123-45
[markup.goldmark.renderer]
unsafe= true

######################### navigation ##############################

